Repository wanted-pre-onboarding-frontend-12team/assignment-2-team12, pull requests merged in 2022-10, with the labels that each got.

#3 [#2] 라우터 설정
  src/App.tsx
  src/router/index.tsx
  src/router/routePath.ts
  src/utils/checkArray.ts
Labels: ✨ Feature

#7 Feature/loading
  src/asset/Spinner.gif
  src/components/Loading/index.tsx
  src/components/Loading/styled.ts
  src/pages/Error/index.tsx
Labels: ✨ Feature

#14 [#6] IssueDetail 페이지에서 사용할 프로필 Avartar 컴포넌트 구현
  src/components/index.ts
  src/components/layout/Header/index.tsx
  src/components/shared/Anchor/index.tsx
  src/components/shared/Anchor/styled.ts
  src/components/shared/Avatar/index.tsx
  src/components/shared/Avatar/styled.ts
  src/router/index.tsx
Labels: ✨ Feature, 💄 UI, 🚑 Bugfix

#16 :ambulance: 화면 안나오던 에러 해결
  src/App.tsx
  src/constants/IssueProvider.tsx
  src/index.tsx
Labels: 🚑 Bugfix

#17 [#5] 타이틀 컴포넌트 구현
  src/shared/Title/index.tsx
  src/shared/Title/styled.ts
Labels: ✨ Feature

#18 [#4] 페이지 공통으로 사용할 Header 컴포넌트 구현
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/index.tsx
  src/router/index.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 💄 UI, 🚑 Bugfix

#22 [#15] 이슈 컴포넌트 구현
  src/components/feature/Issue/index.tsx
  src/components/feature/Issue/styled.ts
  src/components/feature/IssueComment/index.tsx
  src/components/feature/IssueComment/speech-bubble.svg
  src/components/feature/IssueComment/styled.ts
  src/components/feature/IssueNumber/index.tsx
  src/components/feature/IssueNumber/styled.ts
  src/components/feature/IssueTime/index.tsx
  src/components/feature/IssueTime/styled.ts
  src/components/feature/IssueWriter/index.tsx
  src/components/feature/IssueWriter/styled.ts
  src/components/index.ts
  src/pages/IssueList/index.tsx
  src/router/index.tsx
  src/shared/Title/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/dateFormat.ts
Labels: ✨ Feature, 💄 UI

#23 [#13] Context api를 사용한 로딩, 에러 상태 관리
  src/App.tsx
  src/components/Loading/index.tsx
  src/constants/IssueProvider.tsx
  src/constants/StatusProvider.tsx
  src/constants/useStatus.ts
Labels: ✨ Feature, 🌐 API

#24 :lipstick: 이슈 메인페이지 레이아웃 작업
  src/components/feature/Issue/styled.ts
  src/pages/IssueList/index.tsx
  src/pages/IssueList/styled.ts
Labels: 💄 UI

#25 [#19] AdsBanner 컴포넌트 UI 구현
  src/components/feature/AdsBanner/index.tsx
  src/components/feature/AdsBanner/styled.ts
  src/components/index.ts
  src/router/index.tsx
Labels: 💄 UI

#28 [#27] 이슈디테일 컴포넌트 추가
  src/pages/IssueDetail/index.tsx
  src/pages/IssueDetail/styled.ts
  src/router/index.tsx
Labels: 💄 UI

#21 [#20] 무한 스크롤 구현
  src/apis/Issue.ts
  src/components/feature/AdsBanner/styled.ts
  src/components/feature/Issue/index.tsx
  src/constants/IssueProvider.tsx
  src/pages/IssueList/index.tsx
  src/pages/IssueList/useInfinityScroll.tsx
  src/shared/Title/index.tsx
Labels: ✨ Feature

#32 [#26] IssueDetailBody 컴포넌트 구현
  package.json
  src/components/feature/MarkdownRenderer/index.tsx
  src/components/feature/MarkdownRenderer/styled.ts
  src/components/index.ts
  src/pages/IssueDetail/index.tsx
  src/pages/index.ts
  src/router/index.tsx
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: ✨ Feature, 💄 UI

#34 Assignment 2 - Release 1.0.0
  .editorconfig
  package.json
  public/_redirects
  src/App.tsx
  src/apis/Issue.ts
  src/asset/Spinner.gif
  src/components/Loading/index.tsx
  src/components/Loading/styled.ts
  src/components/feature/AdsBanner/index.tsx
  src/components/feature/AdsBanner/styled.ts
  src/components/feature/Issue/index.tsx
  src/components/feature/Issue/styled.ts
  src/components/feature/IssueComment/index.tsx
  src/components/feature/IssueComment/speech-bubble.svg
  src/components/feature/IssueComment/styled.ts
  src/components/feature/IssueHeader/index.tsx
  src/components/feature/IssueHeader/styled.ts
  src/components/feature/IssueNumber/index.tsx
  src/components/feature/IssueNumber/styled.ts
  src/components/feature/IssueTime/index.tsx
  src/components/feature/IssueTime/styled.ts
  src/components/feature/IssueWriter/index.tsx
  src/components/feature/IssueWriter/styled.ts
  src/components/feature/MarkdownRenderer/index.tsx
  src/components/feature/MarkdownRenderer/styled.ts
  src/components/index.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/components/layout/index.tsx
  src/components/layout/styled.ts
  src/components/shared/Anchor/index.tsx
  src/components/shared/Anchor/styled.ts
  src/components/shared/Avatar/index.tsx
  src/components/shared/Avatar/styled.ts
  src/constants/IssueProvider.tsx
  src/constants/StatusProvider.tsx
  src/constants/useStatus.ts
  src/index.tsx
  src/pages/Error/index.tsx
  src/pages/IssueDetail/index.tsx
  src/pages/IssueDetail/styled.ts
  src/pages/IssueList/index.tsx
  src/pages/IssueList/styled.ts
  src/pages/IssueList/useInfinityScroll.tsx
  src/pages/index.ts
  src/router/index.tsx
  src/router/routePath.ts
  src/shared/Title/index.tsx
  src/shared/Title/styled.ts
  src/styles/GlobalStyle.tsx
  src/styles/index.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/checkArray.ts
  src/utils/dateFormat.ts
  src/utils/interface.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API, 🐛 Bug, 💄 UI, 🚑 Bugfix

#38 Assignment 2 - Release 1.0.1
  src/pages/IssueDetail/index.tsx
Labels: 🐛 Bug, 🚑 Bugfix
